import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
#
# Requires:
#   voters_kepler_ready.csv           — voter-level coverage tags
#   OR_coverage_summary_v2.csv        — generated by coverage_analysis.py
#   OR_transit_bootstrap_coverage.csv — generated by transit_bootstrap_coverage.py
#
# Produces all charts and summary CSVs for the baseline analysis presentation.

VOTERS_CSV = "voters_kepler_ready.csv"
COVERAGE_CSV = "OR_coverage_summary_v2.csv"
BOOTSTRAP_CSV = "OR_transit_bootstrap_coverage.csv"
OUTPUT_DIR = "data/charts"

# Colors
COVERED_COLOR = "#4BB543"
NOT_COVERED_COLOR = "#DC3C3C"
DRIVE_COLOR = "#4B96D2"
TRANSIT_COLOR = "#E3970A"
PLATEAU_COLOR = "#FF2D2D"
STATE_LINE_COLOR = "#ffffff"

# Thresholds
COVERAGE_THRESHOLD = 95.0
LOW_TRANSIT_THRESHOLD = 25.0
PLATEAU_THRESHOLD_PCT = 1.0

DRIVE_COLORS = {10: "#a8d4f5", 15: "#4B96D2", 20: "#1a5a96"}
TRANSIT_COLORS = {15: "#f5d08a", 30: "#E3970A", 45: "#8a5500"}
TRANSIT_THRESHOLDS = [15, 30, 45, 60, 120, 180, 240]

# Snapshot for bar charts
SNAPSHOT_WEEKDAY = "Tuesday"
SNAPSHOT_TIME = "18:00"

# Time-of-day line charts
TIME_ORDER = ["Monday 18:00", "Tuesday 8:00", "Tuesday 13:00", "Tuesday 18:00"]
TIME_LABELS_SHORT = ["Mon 18:00", "Tue 08:00", "Tue 13:00", "Tue 18:00"]

TARGET_WEEKDAY = "Tuesday"
TARGET_TIME = "18:00"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ===========================================================================
# LOAD DATA
# ===========================================================================

# ---------------------------------------------------------------------------
# Voter file
# ---------------------------------------------------------------------------

print("Loading voters...")
df = pd.read_csv(VOTERS_CSV)
df = df[df["county"].str.upper() != "WALLA WALLA"]
print(f"  Total voters: {len(df):,}")

df["drive_covered"] = df["drive_zone"] != "Not covered"
df["transit_covered"] = df["transit_zone"] != "Not covered"
df["either_covered"] = df["drive_covered"] | df["transit_covered"]
df["neither_covered"] = ~df["either_covered"]
df["drive_only"] = df["drive_covered"] & ~df["transit_covered"]
df["transit_only"] = df["transit_covered"] & ~df["drive_covered"]
df["both_covered"] = df["drive_covered"] & df["transit_covered"]
total = len(df)

# ---------------------------------------------------------------------------
# Coverage summary
# ---------------------------------------------------------------------------

print("Loading coverage summary...")
cov = pd.read_csv(COVERAGE_CSV)
cov = cov[cov["county"].str.upper() != "WALLA WALLA"] if "county" in cov.columns else cov
cov["time_label"] = cov["weekday"] + " " + cov["time"]

cov_snapshot = cov[
    (cov["weekday"] == SNAPSHOT_WEEKDAY) & (cov["time"] == SNAPSHOT_TIME) & (cov["group"] == "county")
].copy()

drive_df = cov[cov["mode"] == "driving"].copy()

# ---------------------------------------------------------------------------
# Bootstrap data
# ---------------------------------------------------------------------------

print("Loading bootstrap data...")
boot = pd.read_csv(BOOTSTRAP_CSV)
boot = boot[boot["county"].str.upper() != "WALLA WALLA"]

county_transit_accessible = (
    boot[boot["group"] == "county"]
    .groupby("county")["covered"]
    .max()
    .reset_index()
    .rename(columns={"covered": "transit_accessible"})
)
county_totals = boot[boot["group"] == "county"][["county", "total"]].drop_duplicates("county")
county_transit_accessible = county_transit_accessible.merge(county_totals, on="county", how="left")
county_transit_accessible["transit_accessible_pct"] = (
    100 * county_transit_accessible["transit_accessible"] / county_transit_accessible["total"]
).round(1)

low_transit = set(
    county_transit_accessible[county_transit_accessible["transit_accessible_pct"] < LOW_TRANSIT_THRESHOLD][
        "county"
    ].str.upper()
)

flagged = county_transit_accessible[county_transit_accessible["transit_accessible_pct"] < LOW_TRANSIT_THRESHOLD][
    ["county", "transit_accessible_pct"]
].sort_values("transit_accessible_pct")

transit_state_boot = boot[
    (boot["mode"] == "public_transport")
    & (boot["weekday"] == TARGET_WEEKDAY)
    & (boot["time"] == TARGET_TIME)
    & (boot["group"] == "statewide")
].copy()
transit_state_boot = (
    transit_state_boot[transit_state_boot["minutes"].isin(TRANSIT_THRESHOLDS)]
    .sort_values("minutes")
    .reset_index(drop=True)
)

transit_county_boot = boot[
    (boot["mode"] == "public_transport")
    & (boot["weekday"] == TARGET_WEEKDAY)
    & (boot["time"] == TARGET_TIME)
    & (boot["group"] == "county")
].copy()
transit_county_boot = transit_county_boot[transit_county_boot["minutes"].isin(TRANSIT_THRESHOLDS)]

# Plateau detection
transit_state_boot["covered_prev"] = transit_state_boot["covered"].shift(1)
transit_state_boot["incremental_voters"] = transit_state_boot["covered"] - transit_state_boot["covered_prev"]
transit_state_boot["incremental_pct"] = (
    100 * transit_state_boot["incremental_voters"] / transit_state_boot["total"]
).round(2)

plateau_rows = transit_state_boot[transit_state_boot["incremental_pct"] < PLATEAU_THRESHOLD_PCT].dropna()
if len(plateau_rows) > 0:
    plateau_minutes = plateau_rows.iloc[0]["minutes"]
    plateau_covered = plateau_rows.iloc[0]["covered"]
    plateau_pct = plateau_rows.iloc[0]["percent_covered"]
    print(f"  Plateau at {plateau_minutes} min — {int(plateau_covered):,} voters ({plateau_pct:.1f}%)")
else:
    plateau_minutes = None
    print("  No plateau detected")

# ---------------------------------------------------------------------------
# County summary from voter file
# ---------------------------------------------------------------------------

county = (
    df.groupby("county")
    .agg(
        total_voters=("drive_covered", "count"),
        drive_covered=("drive_covered", "sum"),
        transit_covered=("transit_covered", "sum"),
        neither_covered=("neither_covered", "sum"),
        both_covered=("both_covered", "sum"),
    )
    .reset_index()
)
county["drive_pct"] = (100 * county["drive_covered"] / county["total_voters"]).round(1)
county["transit_pct"] = (100 * county["transit_covered"] / county["total_voters"]).round(1)
county["neither_pct"] = (100 * county["neither_covered"] / county["total_voters"]).round(1)
county["drive_not_covered"] = county["total_voters"] - county["drive_covered"]
county["transit_not_covered"] = county["total_voters"] - county["transit_covered"]

drive_20_snapshot = cov_snapshot[(cov_snapshot["mode"] == "driving") & (cov_snapshot["minutes"] == 20)][
    ["county", "percent_covered"]
].rename(columns={"percent_covered": "drive_20_pct"})
county_order = drive_20_snapshot.sort_values("drive_20_pct")["county"].tolist()
under95_counties = county[county["drive_pct"] < COVERAGE_THRESHOLD]["county"].tolist()
under95_order = [c for c in county_order if c in under95_counties]

# Restate transit coverage against transit-accessible denominator
transit_df = cov[cov["mode"] == "public_transport"].copy()
transit_df = transit_df.merge(county_transit_accessible[["county", "transit_accessible"]], on="county", how="left")
total_transit_accessible = county_transit_accessible["transit_accessible"].sum()
transit_df["percent_covered_restated"] = (transit_df["covered"] / transit_df["transit_accessible"] * 100).clip(
    upper=100
)
statewide_mask = transit_df["group"] == "statewide"
transit_df.loc[statewide_mask, "percent_covered_restated"] = (
    transit_df.loc[statewide_mask, "covered"] / total_transit_accessible * 100
).clip(upper=100)

# ---------------------------------------------------------------------------
# Statewide summary print
# ---------------------------------------------------------------------------

statewide_summary = pd.DataFrame([
    {"group": "Drive covered", "voters": df["drive_covered"].sum()},
    {"group": "Drive not covered", "voters": (~df["drive_covered"]).sum()},
    {"group": "Transit covered", "voters": df["transit_covered"].sum()},
    {"group": "Transit not covered", "voters": (~df["transit_covered"]).sum()},
    {"group": "Covered by both", "voters": df["both_covered"].sum()},
    {"group": "Drive only", "voters": df["drive_only"].sum()},
    {"group": "Transit only", "voters": df["transit_only"].sum()},
    {"group": "Neither covered", "voters": df["neither_covered"].sum()},
])
statewide_summary["pct"] = (100 * statewide_summary["voters"] / total).round(1)

print(f"\n{'=' * 55}")
print("STATEWIDE COVERAGE SUMMARY")
print(f"{'=' * 55}")
for _, row in statewide_summary.iterrows():
    print(f"  {row['group']:<30} {row['voters']:>10,}  ({row['pct']}%)")
print(f"{'=' * 55}")
print(f"\nCounties below {COVERAGE_THRESHOLD}% drive coverage: {len(under95_counties)}")
print(f"  {', '.join([c.title() for c in sorted(under95_counties)])}")
print(f"\nCounties below {LOW_TRANSIT_THRESHOLD}% transit accessible:")
print(flagged.to_string(index=False))

# ---------------------------------------------------------------------------
# Save summary CSVs
# ---------------------------------------------------------------------------

statewide_summary.to_csv(f"{OUTPUT_DIR}/statewide_summary.csv", index=False)
county.to_csv(f"{OUTPUT_DIR}/county_summary.csv", index=False)
print(f"\nSaved summary CSVs to {OUTPUT_DIR}/")

# ===========================================================================
# SHARED STYLING
# ===========================================================================


def style_ax_dark(ax):
    ax.set_facecolor("#1a1a2e")
    ax.tick_params(colors="white")
    ax.spines["bottom"].set_color("#444")
    ax.spines["left"].set_color("#444")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.yaxis.label.set_color("white")


def style_ax_time(ax):
    style_ax_dark(ax)
    ax.yaxis.set_major_formatter(mticker.PercentFormatter())
    ax.set_ylim(0, 115)
    ax.set_xlim(-0.5, len(TIME_ORDER) - 0.5)
    ax.set_xticks(range(len(TIME_ORDER)))
    ax.set_xticklabels(TIME_LABELS_SHORT, color="white", fontsize=10)
    ax.set_ylabel("% of Voters Covered", color="white", fontsize=11)
    ax.axvline(x=0.5, color="#555", linewidth=0.8, linestyle=":")
    ax.text(0.25, 111, "Mon", color="#aaa", fontsize=8, ha="center")
    ax.text(2.0, 111, "Tuesday", color="#aaa", fontsize=8, ha="center")


x_time = list(range(len(TIME_ORDER)))

# ===========================================================================
# SECTION 1 — STATEWIDE OVERVIEW CHARTS
# ===========================================================================

print("\n--- Statewide overview charts ---")

# ---------------------------------------------------------------------------
# CHART: Statewide horizontal bar — drive vs transit
# ---------------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(12, 5))
fig.patch.set_facecolor("#1a1a2e")
ax.set_facecolor("#1a1a2e")

categories = ["Drive", "Transit"]
covered_pcts = [100 * df["drive_covered"].sum() / total, 100 * df["transit_covered"].sum() / total]
not_covered_pcts = [100 - p for p in covered_pcts]
y = np.arange(2)

ax.barh(y, covered_pcts, height=0.4, color=[DRIVE_COLOR, TRANSIT_COLOR], alpha=0.9, label="Covered")
ax.barh(y, not_covered_pcts, height=0.4, left=covered_pcts, color=NOT_COVERED_COLOR, alpha=0.7, label="Not Covered")
ax.set_yticks(y)
ax.set_yticklabels(categories, color="white", fontsize=12)
ax.set_xlabel("% of Voters", color="white", fontsize=11)
ax.set_title("Statewide Voter Coverage — Drive vs Transit", color="white", fontsize=14, fontweight="bold", pad=15)
ax.xaxis.set_major_formatter(mticker.PercentFormatter())
style_ax_dark(ax)
ax.spines["left"].set_color("#444")
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=10)
leg.get_frame().set_edgecolor("#444")
for i, (cp, ncp) in enumerate(zip(covered_pcts, not_covered_pcts)):
    ax.text(cp / 2, i, f"{cp:.1f}%", ha="center", va="center", color="white", fontsize=11, fontweight="bold")
    ax.text(cp + ncp / 2, i, f"{ncp:.1f}%", ha="center", va="center", color="white", fontsize=11, fontweight="bold")

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/statewide_coverage.png", dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
plt.close()
print("Saved: statewide_coverage.png")

# ===========================================================================
# SECTION 2 — SNAPSHOT BAR CHARTS (Tuesday 18:00)
# ===========================================================================

print("\n--- Snapshot bar charts (Tuesday 18:00) ---")


def county_threshold_bar_chart(mode, thresholds, color_map, title, filename, county_subset=None):
    order = county_subset if county_subset else county_order
    bar_width = 0.7 / len(thresholds)
    x = np.arange(len(order))

    fig, ax = plt.subplots(figsize=(20, 8))
    fig.patch.set_facecolor("#1a1a2e")
    ax.set_facecolor("#1a1a2e")

    for i, minutes in enumerate(thresholds):
        data = (
            cov_snapshot[(cov_snapshot["mode"] == mode) & (cov_snapshot["minutes"] == minutes)]
            .set_index("county")["percent_covered"]
            .reindex(order)
            .fillna(0)
        )
        offset = (i - (len(thresholds) - 1) / 2) * bar_width
        bars = ax.bar(
            x + offset, data.values, width=bar_width, color=color_map[minutes], label=f"≤{minutes} min", alpha=0.9
        )
        for bar in bars:
            h = bar.get_height()
            if h > 0:
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h + 0.5,
                    f"{h:.0f}%",
                    ha="center",
                    va="bottom",
                    fontsize=5,
                    color="white",
                )

    ax.set_xticks(x)
    xticklabels = ax.set_xticklabels([c.title() for c in order], rotation=45, ha="right", fontsize=8)
    for label, cname in zip(xticklabels, order):
        label.set_color("#DC3C3C" if cname.upper() in {c.upper() for c in under95_counties} else "white")

    ax.set_ylabel("% of Voters Covered", color="white", fontsize=11)
    suffix = "" if county_subset else f"\n(counties below {COVERAGE_THRESHOLD:.0f}% shown in red)"
    ax.set_title(f"{title}{suffix}", color="white", fontsize=14, fontweight="bold", pad=15)
    ax.yaxis.set_major_formatter(mticker.PercentFormatter())
    ax.set_ylim(0, 115)
    style_ax_dark(ax)
    ax.axhline(y=COVERAGE_THRESHOLD, color="#DC3C3C", linewidth=0.8, linestyle="--", alpha=0.6)
    ax.text(
        len(order) - 0.5,
        COVERAGE_THRESHOLD + 0.5,
        f"{COVERAGE_THRESHOLD:.0f}%",
        color="#DC3C3C",
        fontsize=8,
        ha="right",
    )
    leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=10)
    leg.get_frame().set_edgecolor("#444")

    plt.tight_layout()
    plt.savefig(f"{OUTPUT_DIR}/{filename}", dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    print(f"Saved: {filename}")


county_threshold_bar_chart(
    mode="driving",
    thresholds=[10, 15, 20],
    color_map=DRIVE_COLORS,
    title="Voter Coverage by County — Drive Time (≤10 / ≤15 / ≤20 min) — Tuesday 18:00",
    filename="county_coverage_drive.png",
)
county_threshold_bar_chart(
    mode="public_transport",
    thresholds=[15, 30, 45],
    color_map=TRANSIT_COLORS,
    title="Voter Coverage by County — Transit Time (≤15 / ≤30 / ≤45 min) — Tuesday 18:00",
    filename="county_coverage_transit.png",
)
county_threshold_bar_chart(
    mode="driving",
    thresholds=[10, 15, 20],
    color_map=DRIVE_COLORS,
    title=f"Counties Below {COVERAGE_THRESHOLD:.0f}% Drive Coverage — Drive Thresholds — Tuesday 18:00",
    filename="under95_county_coverage_drive.png",
    county_subset=under95_order,
)
county_threshold_bar_chart(
    mode="public_transport",
    thresholds=[15, 30, 45],
    color_map=TRANSIT_COLORS,
    title=f"Counties Below {COVERAGE_THRESHOLD:.0f}% Drive Coverage — Transit Thresholds — Tuesday 18:00",
    filename="under95_county_coverage_transit.png",
    county_subset=under95_order,
)

# ---------------------------------------------------------------------------
# Raw counts stacked bar
# ---------------------------------------------------------------------------

county_merged = county.set_index("county").reindex(county_order).reset_index()
x = np.arange(len(county_order))
bar_width = 0.35

fig, ax = plt.subplots(figsize=(18, 8))
fig.patch.set_facecolor("#1a1a2e")
ax.set_facecolor("#1a1a2e")

ax.bar(
    x - bar_width / 2,
    county_merged["drive_covered"],
    width=bar_width,
    color=DRIVE_COLOR,
    label="Drive covered",
    alpha=0.9,
)
ax.bar(
    x - bar_width / 2,
    county_merged["drive_not_covered"],
    width=bar_width,
    bottom=county_merged["drive_covered"],
    color="#DC3C3C",
    label="Drive not covered",
    alpha=0.7,
)
ax.bar(
    x + bar_width / 2,
    county_merged["transit_covered"],
    width=bar_width,
    color=TRANSIT_COLOR,
    label="Transit covered",
    alpha=0.9,
)
ax.bar(
    x + bar_width / 2,
    county_merged["transit_not_covered"],
    width=bar_width,
    bottom=county_merged["transit_covered"],
    color="#b05000",
    label="Transit not covered",
    alpha=0.7,
)

ax.set_xticks(x)
xticklabels = ax.set_xticklabels([c.title() for c in county_order], rotation=45, ha="right", fontsize=8)
for label, cname in zip(xticklabels, county_order):
    label.set_color("#DC3C3C" if cname in under95_counties else "white")
ax.set_ylabel("Number of Voters", color="white", fontsize=11)
ax.set_title(
    "Voter Coverage by County — Raw Counts (Drive ≤20min vs Transit ≤45min)",
    color="white",
    fontsize=14,
    fontweight="bold",
    pad=15,
)
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
style_ax_dark(ax)
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=10)
leg.get_frame().set_edgecolor("#444")

plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/county_coverage_counts.png", dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
plt.close()
print("Saved: county_coverage_counts.png")

# ===========================================================================
# SECTION 3 — UNDER-95% DRIVE COVERAGE CHARTS
# ===========================================================================

print("\n--- Under-95% drive coverage charts ---")

under95 = county[county["drive_pct"] < COVERAGE_THRESHOLD].sort_values("drive_not_covered", ascending=False)

# ---------------------------------------------------------------------------
# Dual axis — uncovered count + % covered line
# ---------------------------------------------------------------------------

fig, ax1 = plt.subplots(figsize=(14, 7))
fig.patch.set_facecolor("#1a1a2e")
ax1.set_facecolor("#1a1a2e")

bars = ax1.bar(
    range(len(under95)),
    under95["drive_not_covered"],
    color=NOT_COVERED_COLOR,
    alpha=0.85,
    label="Voters not covered (drive)",
)
for bar in bars:
    h = bar.get_height()
    ax1.text(
        bar.get_x() + bar.get_width() / 2, h + 30, f"{int(h):,}", ha="center", va="bottom", fontsize=8, color="white"
    )

ax1.set_xticks(range(len(under95)))
ax1.set_xticklabels(under95["county"].str.title(), rotation=35, ha="right", fontsize=9, color="white")
ax1.set_ylabel("Voters Not Covered (Drive)", color=NOT_COVERED_COLOR, fontsize=11)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
ax1.tick_params(axis="y", colors=NOT_COVERED_COLOR)
ax1.tick_params(axis="x", colors="white")
ax1.spines["bottom"].set_color("#444")
ax1.spines["left"].set_color(NOT_COVERED_COLOR)
ax1.spines["top"].set_visible(False)
ax1.spines["right"].set_color(DRIVE_COLOR)

ax2 = ax1.twinx()
ax2.set_facecolor("#1a1a2e")
ax2.plot(
    range(len(under95)),
    under95["drive_pct"],
    marker="o",
    color=DRIVE_COLOR,
    linewidth=2,
    markersize=7,
    label="Drive % covered",
    zorder=5,
)
for i, val in enumerate(under95["drive_pct"]):
    ax2.text(i, val - 2.5, f"{val:.1f}%", ha="center", fontsize=8, color=DRIVE_COLOR, fontweight="bold")
ax2.set_ylabel("% of Voters Covered (Drive)", color=DRIVE_COLOR, fontsize=11)
ax2.yaxis.set_major_formatter(mticker.PercentFormatter())
ax2.tick_params(axis="y", colors=DRIVE_COLOR)
ax2.set_ylim(0, 100)
ax2.axhline(y=COVERAGE_THRESHOLD, color="#888", linewidth=1, linestyle="--")
ax2.text(
    len(under95) - 0.5,
    COVERAGE_THRESHOLD + 1,
    f"{COVERAGE_THRESHOLD:.0f}% threshold",
    color="#888",
    fontsize=8,
    ha="right",
)
ax2.spines["right"].set_color(DRIVE_COLOR)
ax2.spines["top"].set_visible(False)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
leg = ax1.legend(
    lines1 + lines2, labels1 + labels2, facecolor="#2a2a4e", labelcolor="white", fontsize=9, loc="upper right"
)
leg.get_frame().set_edgecolor("#444")
ax1.set_title(
    f"Counties Below {COVERAGE_THRESHOLD:.0f}% Drive Coverage — Voters Affected vs % Covered",
    color="white",
    fontsize=14,
    fontweight="bold",
    pad=15,
)
fig.subplots_adjust(bottom=0.18, top=0.9, left=0.1, right=0.92)
fig.savefig(f"{OUTPUT_DIR}/under95_drive_dual_axis.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: under95_drive_dual_axis.png")

# ---------------------------------------------------------------------------
# Stacked breakdown — drive/transit/neither
# ---------------------------------------------------------------------------

under95 = under95.copy()
under95["drive_only_seg"] = under95["drive_covered"] - under95["both_covered"]
under95["transit_only_seg"] = under95["transit_covered"] - under95["both_covered"]
under95_tv = under95.sort_values("total_voters", ascending=False)
x_u = np.arange(len(under95_tv))

fig, ax = plt.subplots(figsize=(14, 7))
fig.patch.set_facecolor("#1a1a2e")
ax.set_facecolor("#1a1a2e")

ax.bar(x_u, under95_tv["both_covered"], color="#4BB543", alpha=0.9, label="Covered by both")
ax.bar(
    x_u,
    under95_tv["drive_only_seg"],
    bottom=under95_tv["both_covered"],
    color=DRIVE_COLOR,
    alpha=0.9,
    label="Drive only",
)
ax.bar(
    x_u,
    under95_tv["transit_only_seg"],
    bottom=under95_tv["both_covered"] + under95_tv["drive_only_seg"],
    color=TRANSIT_COLOR,
    alpha=0.9,
    label="Transit only",
)
ax.bar(
    x_u,
    under95_tv["neither_covered"],
    bottom=under95_tv["both_covered"] + under95_tv["drive_only_seg"] + under95_tv["transit_only_seg"],
    color=NOT_COVERED_COLOR,
    alpha=0.9,
    label="Neither covered",
)

ax.set_xticks(x_u)
ax.set_xticklabels(under95_tv["county"].str.title(), rotation=35, ha="right", fontsize=9, color="white")
ax.set_ylabel("Number of Voters", color="white", fontsize=11)
ax.set_title(
    f"Coverage Breakdown — Counties Below {COVERAGE_THRESHOLD:.0f}% Drive Coverage",
    color="white",
    fontsize=14,
    fontweight="bold",
    pad=15,
)
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
style_ax_dark(ax)
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=9, loc="upper right")
leg.get_frame().set_edgecolor("#444")
fig.subplots_adjust(bottom=0.18, top=0.9, left=0.1, right=0.95)
fig.savefig(f"{OUTPUT_DIR}/under95_coverage_breakdown.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: under95_coverage_breakdown.png")

# Under-95% summary CSV
under95_table = (
    county[county["drive_pct"] < COVERAGE_THRESHOLD]
    .sort_values("drive_not_covered", ascending=False)[
        ["county", "total_voters", "drive_pct", "drive_not_covered", "transit_pct", "neither_covered", "neither_pct"]
    ]
    .rename(
        columns={
            "county": "County",
            "total_voters": "Total Voters",
            "drive_pct": "Drive % Covered",
            "drive_not_covered": "Drive Uncovered",
            "transit_pct": "Transit % Covered",
            "neither_covered": "Neither Covered",
            "neither_pct": "Neither %",
        }
    )
)
under95_table["County"] = under95_table["County"].str.title()
under95_table.to_csv(f"{OUTPUT_DIR}/under95_county_focus.csv", index=False)
print("Saved: under95_county_focus.csv")

# ===========================================================================
# SECTION 4 — TIME-OF-DAY LINE CHARTS
# ===========================================================================

print("\n--- Time-of-day line charts ---")

# ---------------------------------------------------------------------------
# Statewide drive — all thresholds
# ---------------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(11, 6))
fig.patch.set_facecolor("#1a1a2e")

for minutes in [10, 15, 20]:
    series = (
        drive_df[(drive_df["minutes"] == minutes) & (drive_df["group"] == "statewide")]
        .set_index("time_label")["percent_covered"]
        .reindex(TIME_ORDER)
    )
    ax.plot(
        x_time,
        series.values,
        marker="o",
        linewidth=2.5,
        markersize=8,
        color=DRIVE_COLORS[minutes],
        label=f"Drive ≤{minutes} min",
    )
    for i, val in enumerate(series.values):
        ax.text(i, val + 1.5, f"{val:.1f}%", ha="center", fontsize=8, color=DRIVE_COLORS[minutes])

style_ax_time(ax)
ax.set_title(
    "Statewide Drive Coverage by Time of Day — All Thresholds", color="white", fontsize=14, fontweight="bold", pad=15
)
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=10)
leg.get_frame().set_edgecolor("#444")
fig.subplots_adjust(bottom=0.12, top=0.9, left=0.1, right=0.95)
fig.savefig(f"{OUTPUT_DIR}/statewide_drive_all_thresholds.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: statewide_drive_all_thresholds.png")

# ---------------------------------------------------------------------------
# Statewide transit — all thresholds (restated against transit-accessible pop)
# ---------------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(11, 6))
fig.patch.set_facecolor("#1a1a2e")

for minutes in [15, 30, 45]:
    series = (
        transit_df[(transit_df["minutes"] == minutes) & (transit_df["group"] == "statewide")]
        .set_index("time_label")["percent_covered_restated"]
        .reindex(TIME_ORDER)
    )
    ax.plot(
        x_time,
        series.values,
        marker="s",
        linewidth=2.5,
        markersize=8,
        color=TRANSIT_COLORS[minutes],
        label=f"Transit ≤{minutes} min",
    )
    for i, val in enumerate(series.values):
        ax.text(i, val + 1.5, f"{val:.1f}%", ha="center", fontsize=8, color=TRANSIT_COLORS[minutes])

style_ax_time(ax)
ax.set_title(
    "Statewide Transit Coverage by Time of Day — All Thresholds\n"
    f"(% of transit-accessible voters; n={int(total_transit_accessible):,} of {int(county_totals['total'].sum()):,})",
    color="white",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=10)
leg.get_frame().set_edgecolor("#444")
fig.subplots_adjust(bottom=0.12, top=0.88, left=0.1, right=0.95)
fig.savefig(f"{OUTPUT_DIR}/statewide_transit_all_thresholds.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: statewide_transit_all_thresholds.png")

# ---------------------------------------------------------------------------
# County drive ≤20 min by time — under-95% highlighted
# ---------------------------------------------------------------------------


def county_drive_time_chart(minutes, title, filename):
    mode_df = drive_df[drive_df["minutes"] == minutes].copy()
    county_only = mode_df[mode_df["group"] == "county"]
    pivot = county_only.pivot_table(index="county", columns="time_label", values="percent_covered").reindex(
        columns=TIME_ORDER
    )
    pivot["mean_cov"] = pivot.mean(axis=1)
    pivot = pivot.sort_values("mean_cov").drop(columns="mean_cov")
    state_line = mode_df[mode_df["group"] == "statewide"].set_index("time_label")["percent_covered"].reindex(TIME_ORDER)
    under95_idx = [c for c in pivot.index if c.upper() in {x.upper() for x in under95_counties}]
    rest_idx = [c for c in pivot.index if c.upper() not in {x.upper() for x in under95_counties}]
    line_styles = ["-", "--", ":", "-.", "-", "--", ":", "-.", "-", "--", ":", "-.", "-", "--", ":"]

    fig, ax = plt.subplots(figsize=(13, 7))
    fig.patch.set_facecolor("#1a1a2e")
    for cname in rest_idx:
        ax.plot(x_time, pivot.loc[cname].values, color="#555577", linewidth=0.8, alpha=0.45)
    cmap = plt.cm.get_cmap("tab10", 10)
    for i, cname in enumerate(under95_idx):
        ax.plot(
            x_time,
            pivot.loc[cname].values,
            marker="o",
            linewidth=2,
            markersize=6,
            color=cmap(i % 10),
            linestyle=line_styles[i],
            label=cname.title(),
        )
    ax.plot(
        x_time,
        state_line.values,
        color="white",
        linewidth=2.5,
        linestyle="--",
        marker="D",
        markersize=7,
        label="Statewide avg",
        zorder=5,
    )
    for i, val in enumerate(state_line.values):
        ax.text(i, val + 1.8, f"{val:.1f}%", ha="center", fontsize=8, color="white", fontweight="bold")
    ax.axhline(y=COVERAGE_THRESHOLD, color="#DC3C3C", linewidth=0.8, linestyle="--", alpha=0.6)
    style_ax_time(ax)
    ax.set_xlim(-0.5, len(TIME_ORDER) - 0.5)
    ax.set_title(
        f"{title}\n(counties below {COVERAGE_THRESHOLD:.0f}% highlighted)",
        color="white",
        fontsize=13,
        fontweight="bold",
        pad=15,
    )
    leg = ax.legend(
        facecolor="#2a2a4e",
        labelcolor="white",
        fontsize=8,
        loc="lower left",
        title=f"Under {COVERAGE_THRESHOLD:.0f}% + Statewide",
        title_fontsize=8,
    )
    leg.get_title().set_color("white")
    leg.get_frame().set_edgecolor("#444")
    fig.subplots_adjust(bottom=0.12, top=0.88, left=0.09, right=0.95)
    fig.savefig(f"{OUTPUT_DIR}/{filename}", dpi=150, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"Saved: {filename}")


county_drive_time_chart(
    minutes=20,
    title="County Drive Coverage by Time of Day — ≤20 min",
    filename="county_drive_20min_by_time.png",
)

# ---------------------------------------------------------------------------
# County transit ≤45 min by time — restated, low-transit flagged
# ---------------------------------------------------------------------------


def county_transit_time_chart(minutes, title, filename):
    mode_df = transit_df[transit_df["minutes"] == minutes].copy()
    county_only = mode_df[mode_df["group"] == "county"]
    pivot = county_only.pivot_table(index="county", columns="time_label", values="percent_covered_restated").reindex(
        columns=TIME_ORDER
    )
    pivot["mean_cov"] = pivot.mean(axis=1)
    pivot = pivot.sort_values("mean_cov").drop(columns="mean_cov")
    state_line = (
        mode_df[mode_df["group"] == "statewide"].set_index("time_label")["percent_covered_restated"].reindex(TIME_ORDER)
    )
    low_idx = [c for c in pivot.index if c.upper() in low_transit]
    rest_idx = [c for c in pivot.index if c.upper() not in low_transit]
    line_styles = ["-", "--", ":", "-.", "-", "--", ":", "-.", "-", "--", ":", "-.", "-", "--", ":"]

    fig, ax = plt.subplots(figsize=(13, 7))
    fig.patch.set_facecolor("#1a1a2e")
    for cname in rest_idx:
        ax.plot(x_time, pivot.loc[cname].values, color="#555577", linewidth=0.8, alpha=0.45)
    cmap = plt.cm.get_cmap("tab10", max(len(low_idx), 1))
    for i, cname in enumerate(low_idx):
        row = pivot.loc[cname]
        ta_pct = county_transit_accessible[county_transit_accessible["county"] == cname][
            "transit_accessible_pct"
        ].values
        ta_str = f" ({ta_pct[0]:.0f}% accessible)" if len(ta_pct) > 0 else ""
        ax.plot(
            x_time,
            row.values,
            marker="o",
            linewidth=2,
            markersize=6,
            color=cmap(i % 10),
            linestyle=line_styles[i],
            label=f"{cname.title()}{ta_str}",
        )
    ax.plot(
        x_time,
        state_line.values,
        color="white",
        linewidth=2.5,
        linestyle="--",
        marker="D",
        markersize=7,
        label="Statewide avg",
        zorder=5,
    )
    for i, val in enumerate(state_line.values):
        ax.text(i, val + 1.8, f"{val:.1f}%", ha="center", fontsize=8, color="white", fontweight="bold")
    style_ax_time(ax)
    ax.set_xlim(-0.5, len(TIME_ORDER) - 0.5)
    ax.set_ylabel("% of Transit-Accessible Voters Covered", color="white", fontsize=11)
    ax.set_title(
        f"{title}\n(% of transit-accessible voters; counties <{LOW_TRANSIT_THRESHOLD:.0f}% accessible flagged)",
        color="white",
        fontsize=13,
        fontweight="bold",
        pad=15,
    )
    leg = ax.legend(
        facecolor="#2a2a4e",
        labelcolor="white",
        fontsize=8,
        loc="lower left",
        title=f"<{LOW_TRANSIT_THRESHOLD:.0f}% accessible + Statewide",
        title_fontsize=8,
    )
    leg.get_title().set_color("white")
    leg.get_frame().set_edgecolor("#444")
    fig.subplots_adjust(bottom=0.12, top=0.88, left=0.09, right=0.95)
    fig.savefig(f"{OUTPUT_DIR}/{filename}", dpi=150, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"Saved: {filename}")


county_transit_time_chart(
    minutes=45,
    title="County Transit Coverage by Time of Day — ≤45 min",
    filename="county_transit_45min_by_time.png",
)

# ===========================================================================
# SECTION 5 — TRANSIT BOOTSTRAP CHARTS
# ===========================================================================

print("\n--- Transit bootstrap charts ---")

x_boot = transit_state_boot["minutes"].values
x_boot_idx = list(range(len(TRANSIT_THRESHOLDS)))

# ---------------------------------------------------------------------------
# Statewide bootstrap curve — incremental bars + cumulative line
# ---------------------------------------------------------------------------

incremental = transit_state_boot["incremental_voters"].fillna(transit_state_boot["covered"].iloc[0]).values

fig, ax1 = plt.subplots(figsize=(12, 6))
fig.patch.set_facecolor("#1a1a2e")
ax1.set_facecolor("#1a1a2e")

ax1.bar(range(len(x_boot)), incremental, color=TRANSIT_COLOR, alpha=0.6, label="New voters added")

ax2 = ax1.twinx()
ax2.set_facecolor("#1a1a2e")
ax2.plot(
    range(len(x_boot)),
    transit_state_boot["covered"].values,
    marker="o",
    color=STATE_LINE_COLOR,
    linewidth=2.5,
    markersize=8,
    label="Cumulative covered",
    zorder=5,
)
for i, (c, p) in enumerate(zip(transit_state_boot["covered"].values, transit_state_boot["percent_covered"].values)):
    ax2.text(
        i,
        c + transit_state_boot["covered"].values[-1] * 0.01,
        f"{int(c):,}\n({p:.1f}%)",
        ha="center",
        fontsize=7,
        color="white",
    )

if plateau_minutes is not None:
    pi = list(x_boot).index(plateau_minutes)
    ax2.axvline(x=pi, color=PLATEAU_COLOR, linewidth=2, linestyle="--", zorder=6)
    ax2.text(
        pi + 0.1,
        transit_state_boot["covered"].values[0],
        f"Plateau\n{plateau_minutes} min\n{int(plateau_covered):,} voters",
        color=PLATEAU_COLOR,
        fontsize=8,
        va="bottom",
    )

ax1.set_xticks(range(len(x_boot)))
ax1.set_xticklabels([f"{m} min" for m in x_boot], color="white", fontsize=10)
ax1.set_ylabel("New Voters Added per Step", color=TRANSIT_COLOR, fontsize=11)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
ax1.tick_params(axis="y", colors=TRANSIT_COLOR)
ax1.tick_params(axis="x", colors="white")
ax1.spines["bottom"].set_color("#444")
ax1.spines["left"].set_color(TRANSIT_COLOR)
ax1.spines["top"].set_visible(False)
ax1.spines["right"].set_color(STATE_LINE_COLOR)

ax2.set_ylabel("Cumulative Voters Covered", color=STATE_LINE_COLOR, fontsize=11)
ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
ax2.tick_params(axis="y", colors=STATE_LINE_COLOR)
ax2.spines["right"].set_color(STATE_LINE_COLOR)
ax2.spines["top"].set_visible(False)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
leg = ax1.legend(
    lines1 + lines2, labels1 + labels2, facecolor="#2a2a4e", labelcolor="white", fontsize=9, loc="upper left"
)
leg.get_frame().set_edgecolor("#444")
ax1.set_title(
    f"Statewide Transit Coverage Bootstrap — {TARGET_WEEKDAY} {TARGET_TIME}\n"
    f"(red line = plateau: <{PLATEAU_THRESHOLD_PCT}% new voters per step)",
    color="white",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
fig.subplots_adjust(bottom=0.12, top=0.88, left=0.1, right=0.9)
fig.savefig(f"{OUTPUT_DIR}/transit_bootstrap_statewide.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: transit_bootstrap_statewide.png")

# ---------------------------------------------------------------------------
# All county bootstrap curves — muted + statewide prominent
# ---------------------------------------------------------------------------

pivot_boot = transit_county_boot.pivot_table(index="county", columns="minutes", values="percent_covered")[
    TRANSIT_THRESHOLDS
]

fig, ax = plt.subplots(figsize=(13, 7))
fig.patch.set_facecolor("#1a1a2e")
ax.set_facecolor("#1a1a2e")

for cname, row in pivot_boot.iterrows():
    ax.plot(x_boot_idx, row.values, color="#555577", linewidth=0.8, alpha=0.4)
ax.plot(
    x_boot_idx,
    transit_state_boot["percent_covered"].values,
    color="white",
    linewidth=3,
    linestyle="--",
    marker="D",
    markersize=8,
    label="Statewide avg",
    zorder=5,
)
for i, val in enumerate(transit_state_boot["percent_covered"].values):
    ax.text(i, val + 2, f"{val:.1f}%", ha="center", fontsize=9, color="white", fontweight="bold")

if plateau_minutes is not None:
    pi = TRANSIT_THRESHOLDS.index(plateau_minutes)
    ax.axvline(x=pi, color=PLATEAU_COLOR, linewidth=2, linestyle="--", alpha=0.8)
    ax.text(pi + 0.05, 5, f"Plateau\n{plateau_minutes} min", color=PLATEAU_COLOR, fontsize=8)

ax.set_xticks(x_boot_idx)
ax.set_xticklabels([f"{m} min" for m in TRANSIT_THRESHOLDS], color="white", fontsize=10)
ax.set_ylabel("% of Voters Covered", color="white", fontsize=11)
ax.yaxis.set_major_formatter(mticker.PercentFormatter())
ax.set_ylim(0, 110)
ax.set_xlim(-0.5, len(TRANSIT_THRESHOLDS) - 0.5)
ax.tick_params(colors="white")
ax.spines["bottom"].set_color("#444")
ax.spines["left"].set_color("#444")
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.set_title(
    f"Transit Coverage Bootstrap — {TARGET_WEEKDAY} {TARGET_TIME}\n(all counties, statewide avg highlighted)",
    color="white",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
leg = ax.legend(facecolor="#2a2a4e", labelcolor="white", fontsize=9, loc="upper left")
leg.get_frame().set_edgecolor("#444")
fig.subplots_adjust(bottom=0.12, top=0.88, left=0.09, right=0.95)
fig.savefig(f"{OUTPUT_DIR}/transit_bootstrap_county.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: transit_bootstrap_county.png")

# ---------------------------------------------------------------------------
# County max transit accessible % — bar chart
# ---------------------------------------------------------------------------

county_max = (
    transit_county_boot.groupby("county").agg(max_covered=("covered", "max"), total=("total", "first")).reset_index()
)
county_max["transit_accessible_pct"] = (100 * county_max["max_covered"] / county_max["total"]).round(1)
county_max = county_max.sort_values("transit_accessible_pct")

fig, ax = plt.subplots(figsize=(18, 7))
fig.patch.set_facecolor("#1a1a2e")
ax.set_facecolor("#1a1a2e")

bars = ax.bar(range(len(county_max)), county_max["transit_accessible_pct"], color=TRANSIT_COLOR, alpha=0.85)
for bar in bars:
    h = bar.get_height()
    ax.text(
        bar.get_x() + bar.get_width() / 2, h + 0.3, f"{h:.0f}%", ha="center", va="bottom", fontsize=6, color="white"
    )
ax.set_xticks(range(len(county_max)))
ax.set_xticklabels(county_max["county"].str.title(), rotation=45, ha="right", fontsize=8, color="white")
ax.set_ylabel("Max % Voters Transit Accessible", color="white", fontsize=11)
ax.set_title(
    f"County Transit Accessible Population (Bootstrap Max) — {TARGET_WEEKDAY} {TARGET_TIME}",
    color="white",
    fontsize=14,
    fontweight="bold",
    pad=15,
)
ax.yaxis.set_major_formatter(mticker.PercentFormatter())
ax.set_ylim(0, 115)
ax.tick_params(colors="white")
ax.spines["bottom"].set_color("#444")
ax.spines["left"].set_color("#444")
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
fig.savefig(
    f"{OUTPUT_DIR}/transit_accessible_by_county.png", dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor()
)
plt.close(fig)
print("Saved: transit_accessible_by_county.png")

# ---------------------------------------------------------------------------
# Top 15 — transit-accessible voters NOT covered within 45 min
# ---------------------------------------------------------------------------

transit_45 = boot[
    (boot["mode"] == "public_transport")
    & (boot["minutes"] == 45)
    & (boot["weekday"] == TARGET_WEEKDAY)
    & (boot["time"] == TARGET_TIME)
    & (boot["group"] == "county")
][["county", "covered", "total"]].copy()

transit_45 = transit_45.merge(county_transit_accessible[["county", "transit_accessible"]], on="county", how="left")
transit_45["transit_accessible_not_covered"] = (transit_45["transit_accessible"] - transit_45["covered"]).clip(lower=0)
transit_45["transit_accessible_covered_pct"] = (
    (transit_45["covered"] / transit_45["transit_accessible"] * 100).clip(upper=100).round(1)
)

top15 = transit_45.nlargest(15, "transit_accessible_not_covered")

fig, ax1 = plt.subplots(figsize=(14, 7))
fig.patch.set_facecolor("#1a1a2e")
ax1.set_facecolor("#1a1a2e")

x_t15 = range(len(top15))
bars = ax1.bar(
    x_t15,
    top15["transit_accessible_not_covered"],
    color=TRANSIT_COLOR,
    alpha=0.85,
    label="Transit-accessible voters not covered",
)
for bar, val in zip(bars, top15["transit_accessible_not_covered"]):
    ax1.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 30,
        f"{int(val):,}",
        ha="center",
        va="bottom",
        fontsize=8,
        color="white",
    )

ax1.set_xticks(x_t15)
ax1.set_xticklabels(top15["county"].str.title(), rotation=30, ha="right", fontsize=9, color="white")
ax1.set_ylabel("Transit-Accessible Voters Not Covered", color=TRANSIT_COLOR, fontsize=11)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}"))
ax1.tick_params(axis="y", colors=TRANSIT_COLOR)
ax1.tick_params(axis="x", colors="white")
ax1.spines["bottom"].set_color("#444")
ax1.spines["left"].set_color(TRANSIT_COLOR)
ax1.spines["top"].set_visible(False)
ax1.spines["right"].set_color("#4B96D2")

ax2 = ax1.twinx()
ax2.set_facecolor("#1a1a2e")
ax2.plot(
    x_t15,
    top15["transit_accessible_covered_pct"],
    marker="o",
    color="#4B96D2",
    linewidth=2,
    markersize=7,
    label="% transit-accessible covered",
    zorder=5,
)
for i, val in enumerate(top15["transit_accessible_covered_pct"]):
    ax2.text(i, val - 4, f"{val:.1f}%", ha="center", fontsize=8, color="#4B96D2", fontweight="bold")
ax2.set_ylabel("% of Transit-Accessible Voters Covered", color="#4B96D2", fontsize=11)
ax2.yaxis.set_major_formatter(mticker.PercentFormatter())
ax2.tick_params(axis="y", colors="#4B96D2")
ax2.set_ylim(0, 110)
ax2.spines["right"].set_color("#4B96D2")
ax2.spines["top"].set_visible(False)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
leg = ax1.legend(
    lines1 + lines2, labels1 + labels2, facecolor="#2a2a4e", labelcolor="white", fontsize=9, loc="upper right"
)
leg.get_frame().set_edgecolor("#444")
ax1.set_title(
    f"Counties Where Transit Exists But Drop Sites Are Underpositioned — Top 15\n"
    f"(transit-accessible voters not covered within 45 min, {TARGET_WEEKDAY} {TARGET_TIME})",
    color="white",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
fig.subplots_adjust(bottom=0.18, top=0.88, left=0.1, right=0.92)
fig.savefig(f"{OUTPUT_DIR}/transit_underserved_top15.png", dpi=150, facecolor=fig.get_facecolor())
plt.close(fig)
print("Saved: transit_underserved_top15.png")

# ---------------------------------------------------------------------------
# Save bootstrap summary CSV
# ---------------------------------------------------------------------------

summary = county_max.rename(
    columns={
        "county": "County",
        "max_covered": "Transit Accessible Voters",
        "total": "Total Voters",
        "transit_accessible_pct": "Transit Accessible %",
    }
)
summary["County"] = summary["County"].str.title()
summary.to_csv(f"{OUTPUT_DIR}/transit_accessible_summary.csv", index=False)
print("Saved: transit_accessible_summary.csv")

# ===========================================================================
# DONE
# ===========================================================================

print(f"\n{'=' * 60}")
print(f"TRANSIT ACCESSIBLE POPULATION — {TARGET_WEEKDAY} {TARGET_TIME}")
print(f"{'=' * 60}")
if plateau_minutes:
    print(f"Plateau at:                {plateau_minutes} min")
    print(f"Transit accessible voters: {int(plateau_covered):,} ({plateau_pct:.1f}%)")
print(f"{'=' * 60}")

print(f"\nAll {len(os.listdir(OUTPUT_DIR))} files saved to {OUTPUT_DIR}/")
